version: '3.11.5'
services:
  python:
    image: thassung/a2_python:v0.0.2
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - ./:/root/code
      - .vscode-server:/root/.vscode-server
    command: mlflow server --gunicorn-opts "--workers 4 --timeout 300"
  mlflow:
    image: thassung/a2_mlflow:v0.0.2
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    volumes:
      - ./_mlflow:/mlflow
    ports:
      - 5000:5000
    command: mlflow server --gunicorn-opts "--workers 4 --timeout 300"
    # stop_grace_period: 5m