version: '3.11.5'
services: 
  web: 
    command: python3 app.py
    image: thassung/demoapp:v2.0.0
    environment:
      - HOST=0.0.0.0
      - PORT=80
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.web-st124323.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is web-st124323
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.web-st124323.rule=Host(`st124323.ml2023.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.web-st124323.tls=true
      - traefik.http.routers.web-st124323.tls.certresolver=production
      - traefik.http.routers.web-st124323.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true