version: '3.11.5'
services: 
  dash: 
    # command: tail -f /dev/null
    command: python3 app/app.py
    image: thassung/demoapp:v3.0.0
    build:
      context: .
      dockerfile: .Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 4000:80
    # volumes:
    #   - ./app:/root/app
    env_file:
      - .env

volumes:
  vscode_server: