version: '3.11.5'
services: 
  web: 
    command: python3 app.py
    image: thassung/demoapp:v2.0.2
    build:
      context: .
      dockerfile: dash.Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 4000:80